apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels: 
    name: pod1
    myapp: testpod
spec:
  containers:
  - name: myapp
    image: nginx
    ports:
      - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels: 
    name: pod2
    myapp: testpod
spec:
  containers:
  - name: myapp1
    image: nginx
    ports:
      - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: pod3
  
spec:
  containers:
  - name: myapp3
    image: nginx
    ports:
      - containerPort: 80